export const Experience = [
    {
        number: 1,
        business: 'Indra Colombia',
        countMonth: 16,
        initial_date: 'feb 2019',
        final_date: undefined,
        state: true,
        position: 'Ingeniero de Sistemas Grado 2 – Líder y Desarrollador para Área de Automatización',
        functions: 'Liderar el área de automatizaciones, gestionando cada uno de los proyectos que sean comprometidos con las distintas operaciones que se manejen en el Datacenter de Claro, adicional desarrolla soluciones por medio de distintos lenguajes de programación y/o plataformas como Ansible, Jenkis, Docker, ManageIQ, etc.',
        color: 'primary',
    },
    {
        number: 2,
        business: 'Indra Colombia',
        countMonth: 18,
        initial_date: 'ago 2018',
        final_date: 'feb 2019',
        state: false,
        position: 'Ingeniero Administrador de Capa Media',
        functions: 'Administrar servicios de aplicación a nivel de Capa Media, como lo son Weblogic 11g/12c, Tomcat, JBoss, etc. Estos servicios están ubicados en gran mayoría en servidores con Sistemas Operativos Unix, dando paso a la creación de variedad de Shell Scripts, Scripts de Python, que dan mayor agilidad al realizar actividades o al realizar monitoreo de los servicios, adicional automatización de informes generando documentos Word, reducción de tareas y creación de monitores a partir de herramientas como Ansible, reduciendo algunos procesos concurrentes en las operaciones.',
        color: 'secondary',
    },
    {
        number: 3,
        business: 'Fundación Universitaria Unipanamericana',
        countMonth: 11,
        initial_date: 'oct 2017',
        final_date: 'ago 2018',
        state: false,
        position: 'Practicante del Área de Audiovisuales',
        functions: 'Dar soporte técnico en servicios audiovisuales y computacionales, preparando las aulas de estudio y sus correspondientes materiales.',
        color: 'primary',
    },
]